# Site settings
title: the odd data guy
email: daignanjm@gmail.com
description: > # My blog.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
enable_retina: false
permalink: :title
nav_list:
  Home : ['Home', '/', 'fa-home']
  Tools : ['Tools', '/category/tooling', 'fa-bookmark']
  DS&ML : ['DS&ML', '/category/dsml', 'fa-bookmark']
  Writing : ['Writing', '/category/writing', 'fa-bookmark']
  About : ['About', '/about', 'fa-anchor']
single_footer: ''
footer_links:
    About: ['About', '/about']

# Build settings
# markdown: kramdown
google_tracking_id: 'UA-104903671-1'
