# Site settings
title: Jean-Michel D.
header-img: img/home-bg.jpg
email: your-email@yourdomain.com
copyright_name: jmdaignan
description: "A portfolio to present my vision on some subjects and to presennt some of my projects"
baseurl: ""
url: "jmdaignan.com"
twitter_username: Daignanjm
github_username:  jeanmidevacc
email_username:  your-email@yourdomain.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
google_tracking_id: 'UA-104903671-1'

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["node_modules"]

gems: [jekyll-paginate, jekyll-feed]
